### ISSUE TITLE
[BUG] Spirit to Hit conversion talents are giving Hit Rating from Base Spirit

### ISSUE THREAD

**Issue by ForgeGit** [JamminL/cata-classic-bugs#861]
#### 1.1. Description
The "Twisted Faith" talent (Shadow tree - Priest) is currently giving hit rating from base spirit. 

  #### 1.2. How to Reproduce
           1. Reach level 19 (min. lvl required to assign points into Twisted Faith)
           2. Assign points into Twisted Faith
           3. Check hit rating and spirit values
  #### 1.3  Source Material
- No gear and one point into Twisted Faith
  - 46 base spirit = 23 hit rating (50% with 1/2 points in Twisted Faith)

![TwistedFaith](https://github.com/JamminL/cata-classic-bugs/assets/75605537/e9ae3c1d-d8eb-4d76-b403-816b343df57d)

#### 2.1. Description
Based on the description, hit rating should be from `items/gear` or `effects/buffs`.

  #### 2.2 Source Material
- An old website suggests the conversion is "excluding base spirit" https://web.archive.org/web/20120112095715/http://shadowpriest.com/viewtopic.php?f=72&t=30989

**Comment by CharWS** [comment]
Is also impacting druid and shaman for their respective spirit to hit conversion talents as noted in https://github.com/JamminL/cata-classic-bugs/issues/954

**Comment by ssabbyccatt** [comment]
Fixed for boomkin as of today

**Comment by CharWS** [comment]
looks to still be broken for shaman

**Comment by CharWS** [comment]
https://cdn.discordapp.com/attachments/1227334512141144135/1230710170439516243/image.png?ex=66232baa&is=6621da2a&hm=bdbe5d91441d8127fa6f121308cb22c57a3b44c1634f8a4cc7f592f8fad29676&
https://cdn.discordapp.com/attachments/1227334512141144135/1230710190467190804/image.png?ex=66344f2e&is=6621da2e&hm=e2bfe720dfe88750897e0668f248fb794e963cf51155dcee308cd287d7c14f4b&
appears still broken for druid as well

**Comment by ssabbyccatt** [comment]
> https://cdn.discordapp.com/attachments/1227334512141144135/1230710170439516243/image.png?ex=66232baa&is=6621da2a&hm=bdbe5d91441d8127fa6f121308cb22c57a3b44c1634f8a4cc7f592f8fad29676& https://cdn.discordapp.com/attachments/1227334512141144135/1230710190467190804/image.png?ex=66344f2e&is=6621da2e&hm=e2bfe720dfe88750897e0668f248fb794e963cf51155dcee308cd287d7c14f4b& appears still broken for druid as well

Really interesting -- it was working right when the beta came up earlier tonight, but I just checked and it isn't working anymore for me, either. It worked for myself and another user in the druid discord, though we did not grab screenshots. When it worked for 2 of us, I just assumed it was good to go so I didn't bother grabbing a screenshot. RIP
![Screenshot 2024-04-18 230640](https://github.com/JamminL/cata-classic-bugs/assets/99249505/1f8978d2-c081-4cef-8a4a-1bb57ec60f0a)

**Comment by ssabbyccatt** [comment]
![Screenshot 2024-04-22 163143](https://github.com/JamminL/cata-classic-bugs/assets/99249505/b9bda253-e690-4794-938f-0edf8871382e)
Appears to be fixed for boomkin again as of 4/22

**Comment by ssabbyccatt** [comment]
![Screenshot 2024-04-22 163037](https://github.com/JamminL/cata-classic-bugs/assets/99249505/b8e8fca6-4e4b-4e27-9991-15c3db30dc96)
Appears to be fixed again for Moonkin as of 4/22

**Comment by raethkcj** [comment]
Confirmed fixed for Ele too
![image](https://github.com/JamminL/cata-classic-bugs/assets/7716908/de4170a6-9522-4ec3-8140-9488a75b79da)
